name = "forage"
version = "0.1.0"
license = "MIT"
author = "Sebastian G. Mutz"
maintainer = "sebastian@mutz.science"
copyright = "Copyright 2025, Sebastian G. Mutz"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
[dependencies]
stdlib = "*"
